fritz
I got it working with the dockerized version of SkyPortal! However, several things need to be addressed:
- See [this SkyPortal issue](https://github.com/skyportal/skyportal/issues/377)
- See [this SkyPortal issue](https://github.com/skyportal/skyportal/issues/378)
- need to put in a db password into the config file(s). 
With these fixes, running
```bash
./fritz run --init
./fritz run
docker exec -it kowalski_ingester_1 python -m pytest -s test_ingester.py
```
should execute a barebones end-to-end example.
=> barebones end-to-end example

CONTRIBUTING.md, doc/developer.md
Closes [ch-591].
- There is now a rudimentary website at https://fritz-marshal.org
- The docs are rendered to https://fritz-marshal.org/doc
=> Contributor documentation

doc/Makefile, fritz
These `.json` files are not currently copied to the output directory.
This seems to be a problem with the way recommonmark handles links with
extensions.
See also https://github.com/readthedocs/recommonmark/issues/130#issuecomment-658632877
=> Add `data` folder to built docs

doc/user_guide.md, extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/static/js/components/Filter.jsx, extensions/skyportal/static/js/components/SaveAlertButton.jsx, extensions/skyportal/static/js/components/ZTFAlert.jsx, extensions/skyportal/static/js/ducks/alert.js, extensions/skyportal/static/js/ducks/kowalski_filter.js, fritz
In this PR:
- `extensions/skyportal/skyportal/handlers/api/alert.py`:
- new endpoint `ZTFAlertHandler.post` to save ZTF alerts as sources by their `objectId`, e.g. `api('POST', '<fritz_instance_location>/api/alerts/ztf/<objectId>'), {"candid": <candid>, "group_ids": <list of group ids>}`. Under the hood, F pulls the required data from K, massages them, and posts to SP's `/api/sources`, `/api/photometry`, and `/api/thumbnail`. If `candid` is not provided, metadata and thumbnails will be pulled from the latest alert/candid. If no list of group_ids is provided, the object will be saved to all user's groups
- async api calls to Kowalski using `tornado.httpclient` instead of `requests`
- `extensions/skyportal/static/js/components/ZTFAlert.jsx`
- Re-skin that makes the page look a lot more like …
=> Save ZTF alerts as sources by objectId

extensions/skyportal/skyportal/handlers/api/alert.py
This fixes a bug in a situation like this:
- user has access to `stream_id`'s 1 and 2
- new alerts come in from `stream_id` 3 that have a 3-sigma detection in `prv_candidates` that came after the last alert the user has access to
- need to grab the `candid` of that last alert, and not the max of all candids (the 3-sigma detection does not come with thumbnails)
=> Fix subtle bug in /api/ztf/<objectId>.POST

extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/static/js/components/SaveAlertButton.jsx, fritz.defaults.yaml
In this PR:
- Allow saving ZTF alerts to any group using `/api/alerts/ztf/<objectId>.POST`. Group (ZTF alert) stream access is respected when saving the photometry.
- Make the `SAVE` button in the modal inactive while the submission is ongoing
- Pin latest SP and K
- Update default config
=> Allow saving ZTF alerts to any group, respecting stream access

extensions/skyportal/skyportal/handlers/api/alert.py, fritz
In this PR:
- In `/api/alerts/ztf/<oid>/aux`, run a cone search on the TNS collection on Kowalski and report the results as a part of the `cross_matches` field.
=> TNS cross-match data

extensions/skyportal/skyportal/handlers/api/alert.py
Introduce an option to return all fields in Kowalski queries. For example,
`/api/alerts/ztf/ZTF20abydkrl?includeAllFields=true`
`/api/alerts/ztf/ZTF20abydkrl/aux?includeAllFields=true`
=> includeAllFields option in K queries

extensions/skyportal/skyportal/handlers/api/alert.py, fritz.defaults.yaml
...instead of zeros as is currently done.
Example:
After:
Before:
=> Replace nans with median in thumbnails

extensions/skyportal/skyportal/handlers/api/alert.py
On the example of ZTF20actodrq:
After:
Before:
=> Remove dubiously large values in thumbnails

fritz
This relies on https://github.com/skyportal/skyportal/pull/1456 being merged and pinned first.
Update: that has now been merged. This should be good to go.
=> Customize title and URL of API docs

extensions/skyportal/skyportal/handlers/api/alert.py
Realized that we still need RA's and Dec's of all prv_candidates for the TNS query, so did a refactor to pull those anyway on the backend, and then just drop `prv_candidates` if `includePrvCandidates=false` to reduce traffic. Also, `get_query_argument` always returns strings, took that into account.
=> Redo adding includePrvCandidates param to /api/alerts/ztf/<oid>/aux

doc/developer.md
Fixed minor typo in Fritz documentation on Developer Guidelines page that specified the incorrect upstream repo.
=> update git remote command to use correct repo

.requirements/dev.txt, fritz, fritz.defaults.yaml
Two errors I ran into when spinning up Fritz locally are addressed here:
- The Kowalski token was being written to the configs encoded as binary (with `!!binary`) and that didn't agree with SP.
- The `homepage_grid` parameter was missing for the default app configs, leading to an error when trying to build the homepage from its template file. 
The rest of the changes are just from black, I think - not sure why they weren't changed before.
=> Fix configuration bugs

fritz.defaults.yaml
Just realized that there is another issue I didn't catch in the last PR. The homepage configs are not indented enough, and they were technically not part of `skyportal.app` as they should be. Guess I fixed this at some point in `fritz.yaml` and forgot to propagate it to the defaults.
=> Fix indentation issue in configs

extensions/skyportal/static/js/components/VegaPlotZTFAlert.jsx, extensions/skyportal/static/js/components/ZTFAlert.jsx
- Re-style the position text to better match the source page on SP, i.e. with colon separators
- Put the Alerts table in an Accordion tab so user can just close the tab to get to the cross matches instead of scrolling (the tables can get very long on mobile since the MUI DataTable essentially flips rows and columns as its responsiveness strategy)
- Limit the size of the Vega plot for the alert when a phone in portrait mode is detected (the narrowest screen types).
=> Improve the ZTF Alert page

fritz.defaults.yaml
Close skyportal/skyportal#1539.
Now that skyportal/skyportal#1754 has been merged, we can re-enable resizing for dashboard widgets and have it work properly.
=> Enable dashboard widgets resizing

.gitmodules, fritz.defaults.yaml
This enables slack integration and relaxes strict permission checking on skyportal
=> pin fritz to version of skyportal with slack integration

.github/workflows/build-docker.yml, .github/workflows/build-test-doc_upload.yaml, .github/workflows/test-integration.yaml, fritz, fritz.defaults.yaml, requirements.txt, tools/check_environment.py
In this PR:
- Refactored the `fritz` utility to use `python-fire` instead of `argparse`. This does not touch the logic in `fritz` yet, it is meant to improve the code's readability and maintainability, e.g. we will now be able to utilize typing.
- The `fritz` utility now first checks if python requirements are satisfied in addition to checking system dependencies.
=> Refactor fritz utility to use python-fire

extensions/skyportal/skyportal/app_server_fritz.py
The error:
```
QueuePool limit of size 5 overflow 10 reached, connection timed out,
timeout 30 (Background on this error at: http://sqlalche.me/e/13/3o7r)
```
This happened because we switched to a single-session-per-request
model.  Now, for each thread on the app server, there will be one or
more session (and, thus, one or more database connection).
Our current SQLAlchemy pool limits are: 5 connections,
with an overrun of 10 (i.e., a maximum of 15 database connections).
This is roughly correct: we run 8 instances of the application, and
8 * 15 = 120 (slightly larger than the 100 connections allowed to
Postgres by default).
With the new thread model, we will have at least nr_threads * nr_apps
connections.  Tornado uses asyncio, which defaults to 5 * NR_CPU
threads, and we have 8 CPUs. …
=> Try to avoid running out of database connections

fritz, tools/check_environment.py, tools/status.py
This is a start towards cleaning up the fritz CLI output.
1. Remove unnecessary prints from fire
2. Wrap dependency checks and submodule inits with `status`
This is not implemented here, but I recommend we standardize the way we call `subprocess.run` and wrap these in status calls.  This would more clearly indicate where things go wrong (currently, we just exit with an exception).
=> Make Fritz CLI less noisy

.requirements/ext.txt, extensions/skyportal/static/js/components/About.jsx, fritz
We now use `skyportal.utils.gitlog.get_gitlog` to generate the logs, instead
of running `git` manually in a subprocess.
=> Fix SkyPortal git logs; add Kowalski git logs

extensions/skyportal/skyportal/handlers/api/db_stats.py
Namely,
- Number of objects in TNS collection
- Latest object from TNS collection discovery date (UTC)
The TNS watchdog is known to sometimes have issues due to external causes, this should help spot such early.
=> Report K's TNS collection stats in db_stats.py

extensions/skyportal/skyportal/handlers/api/tns_info.py, extensions/skyportal/static/js/components/TNSInfo.jsx
The updated state structure allows us to easily track whether the state corresponds to the source being viewed or whether it needs to be re-fetched.
=> Update TNS info fetching logic & redux state structure

doc/user_guide.md
Luckily, the actual code used in prod has always been fine.
=> Fix typo in docs re: upstream filter pipelines

extensions/skyportal/static/js/components/SourceDesktop.jsx, extensions/skyportal/static/js/components/SourceMobile.jsx
Front end display of redshift_error that was merged on skyportal is overwritten by fritz extensions.  This re-adds the front-end display code to the fritz extensions.
Back-end implementation of redshift_error on fritz has been tested and verified.
=> Updating fritz front-end extensions to implement redshift error display

.github/workflows/build-test-doc_upload.yaml, doc/user_guide.md
Namely, to the Quick start section. Closes #289.
=> Add screen captures on ZTF alerts and light curves to the docs

extensions/skyportal/static/js/components/Alerts.jsx, extensions/skyportal/static/js/components/AlertsSearchButton.jsx, extensions/skyportal/static/js/components/Archive.jsx, extensions/skyportal/static/js/components/ArchiveSearchButton.jsx, extensions/skyportal/static/js/components/SourceDesktop.jsx, extensions/skyportal/static/js/components/SourceMobile.jsx, extensions/skyportal/static/js/ducks/alerts.js, extensions/skyportal/static/js/ducks/archive.js
This PR introduces a button to the source page that, when clicked, submits a request to query alerts within 3 arcseconds of the source in question and redirects to the alerts page to render the results. Other improvements to the alerts page, including a spinner during request processing, and redux state structure updates, are included.
Closes  https://github.com/fritz-marshal/fritz/issues/287
=> Add buttons to search alerts & LC archive near source on source page

.github/workflows/test-integration.yaml
Also increased timeout to 30 minutes in test-integration GA workflow - 25 is not enough anymore now that we test processing two alert streams, ZTF and PGIR.
=> Pin SP - 20210812

extensions/skyportal/static/js/components/SourceDesktop.jsx
ZTF source names are case sensitive!
=> No text transform on possible duplicate buttons

extensions/skyportal/static/js/components/CentroidPlot.jsx, extensions/skyportal/static/js/components/SourceMobile.jsx
This is a port of @kmshin1397's #323 (see for the details) that only updates the Centroid plot (brings in the CentroidPlot.jsx and HR diagram styling changes introduced in skyportal/skyportal#2154), since we still haven't decided what we wanted for the ACAI classifications from that PR.
=> Update Centroid plot

.github/workflows/test-integration.yaml, fritz.defaults.yaml, launcher/commands/build.py, launcher/commands/test.py, tools/check_environment.py
In this PR:
- Bumped up wait times for SP to spin up inside Docker, which for some reason now takes longer than before.
- Set `ssl: False` in the server settings in the default config as otherwise frontend wouldn't load locally (at least on my mac as of 2021/10/01).
- Propagate the `yes` option to Kowalski build operation when doing `./fritz run --init --yes`
- Update docker-compose version check to make it compatible with >v2
- Update SP and K
=> Update K and SP

extensions/skyportal/docker-compose.skyportal.yaml, launcher/commands/doc.py, launcher/commands/run.py, launcher/commands/test.py, launcher/config.py, launcher/skyportal.py
This is the way the SP Dockerfile was intended to be configured.
Inside, it copies this to config.yaml and then fills out templates and
sets up services.
If `config.yaml` is used instead, like we did in Fritz, it gets
overwritten by `docker.yaml` at some point—no good.
=> Use docker.yaml to configure SkyPortal Dockerfile

fritz.defaults.yaml
This PR adds the ZTF forced photometry endpoint to the config.
=> add ztf forced photometry endpoint

fritz.defaults.yaml
This PR adds the gcn pages to the fritz config.
=> Add gcn pages to fritz

fritz.defaults.yaml
We are retiring the 8-year-old pharos and replacing it with minar. The web server is up and running and this should be a
seamless transition. Please let me know when this is deployed so we don't lose SEDM requests through the cracks.
=> Change sedm_endpoint from pharos to minar

fritz.defaults.yaml
This PR adds the galaxy page to the fritz sidebar.
=> add galaxy to fritz sidebar

extensions/skyportal/skyportal/handlers/api/alert.py, fritz.defaults.yaml
There's a bug when using the alerts handler, when the current user cannot access streams because it is detached form a session. 
I opened a `self.Session` that should attach the current user to the new session and let it load streams.
=> Fix Alert user detached from session

extensions/skyportal/skyportal/handlers/api/alert.py
Found another place with detached user that has been causing errors for the `alerts_aux` endpoint.
=> More alert fixes

extensions/skyportal/docker-compose.skyportal.yaml
This PR bumps default postgres in docker-compose to 14.4, required for all of the healpix-alchemy infrastructure.
=> Use newer version of postgres in default compose

fritz.defaults.yaml
This PR adds the LCO archive endpoint to the fritz default config.
=> Add LCO archive endpoint

fritz.defaults.yaml
This PR allows one to set a group_id for GCN which will remember the last entry committed from the kafka stream. Pairs with https://github.com/skyportal/skyportal/pull/3508.
=> set group_id for GCN

fritz.defaults.yaml
This PR changes Archive to Persistent Sources in the left panel, which is a much more intuitive name.
=> Change Archive -> Persistent Sources in panel

extensions/skyportal/skyportal/handlers/api/archive.py
This PR uses get when querying the config in archive.py.
=> Use get when querying config

extensions/skyportal/skyportal/handlers/api/alert.py
This combines with skyportal PR #3534 to allow importing alert.py without a try/catch statement.
=> add alert_available

extensions/skyportal/skyportal/handlers/api/alert.py
When padding a cutout that has been normalized with its median, the median must be recomputed after the normalization.
=> recompute padding fill value after normalization

extensions/skyportal/skyportal/app_server_fritz.py, extensions/skyportal/skyportal/handlers/api/archive.py, extensions/skyportal/static/js/components/SourceAnnotationButtonsPlugins.jsx, extensions/skyportal/static/js/ducks/archive.js
This PR adds an annotation button plugin to fetch SCoPe-generated features from the `ZTF_source_features_DR5` catalog on gloria. The code performs a 2-arcsec cone search around the source's RA and Dec before querying gloria for a set of features. These features, which are then posted to the source as annotations, consist of all the light curve's 'basic stats' along with the ID, field, ccd and quadrant. The current code runs successfully but has the following limitations:
- The single-button nature of the frontend interaction does not permit the user to specify the feature catalog, cone search radius, or specific features to get
- A source can have multiple associated light curves, but since SCoPe features are generated on a per-lightcurve basis, the code currently only gets features from …
=> Annotation button plugin to fetch/post SCoPe features from Kowalski/gloria

extensions/skyportal/static/js/components/SourceAnnotationButtonPlugins.jsx
This PR changes the source of `fetchScopeFeatures` from `source.js` (used during local testing) to `archive.js`. This will enable Scope features to be successfully fetched when clicking the new annotation button.
=> Use archive.js action instead of source.js for Scope features button

fritz.defaults.yaml
As suggested by @stefanv, we shouldn't need to specify database arguments allowing more connections.
=> remove engine args

.requirements/ext.txt, extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/skyportal/handlers/api/archive.py, extensions/skyportal/skyportal/handlers/api/db_stats.py, fritz.defaults.yaml
Needs https://github.com/skyportal/skyportal/pull/4349 to be merged first.
I suggest really trying out the code for this one, there's a lot that could break :)
Locally, I tried each handler and everything seems to work just fine, I can:
- Get alerts from the alerts page
- Visualize individual alerts and save them as as sources from the alerts page
- Get lightcurves from the persistent sources page, where we can now query gloria + melman (meaning DR5 but also now DR16)
- Save lightcurves as sources
- From the source page, get crossmatches with gloria + melman and see them on the centroid plot.
- From the source page, request scope features to be posted as annotations (from ztf features DR5 for now, but can be easily extended to any catalogs with DR`X` in a following PR (or migrated to ztf …
=> Penquins 2.3.1 + SkyPortal 893af747e1b4290e23266b093f883a0d343cf122

extensions/skyportal/skyportal/handlers/api/archive.py, extensions/skyportal/static/js/components/Archive.jsx, extensions/skyportal/static/js/components/ArchiveSearchButton.jsx, extensions/skyportal/static/js/components/SourceAnnotationButtonPlugins.jsx
- hide catalogs that do not start with ZTF_sources_202 (it's enough to cover the 20's)
- Scope annotation import: Allow user to pick scope catalog (DR3, DR5, and soon DR16)
- Archive.py: Allow to still query available instances of Kowalski when some of them aren't accessible, instead of blocking any access.
=> Persistent sources and Scope features interaction: Improvements

extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/skyportal/handlers/api/archive.py, extensions/skyportal/static/js/components/CopyAlertPhotometryDialog.jsx, extensions/skyportal/static/js/components/SaveAlertButton.jsx, extensions/skyportal/static/js/components/ZTFAlert.jsx
- when posting an alert as a source, allow to post the data not only to the associated ZTF source but to any source within 2 arcsec. This will post photometry, but not the thumbnails as the other source could be an alert from WINTER, TURBO, PGIR,... which would replace its thumbnails. We could come up with a better behavior later.
- Thumbnail bugfix: There was a missing f in front of an f-string, rip...
- Sometimes a candid in prv_candidates doesn't exist in the alerts table. When that happens, we use the latest candid instead when posting thumbnails + notify the user.
I would suggest the reviewer to **really test this thoroughly**, as we wouldn't want existing features (see an alert and save it as a source) to not work anymore.
=> Save ZTF alert photometry to other (nearby) sources

extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/static/js/components/ZTFAlert.jsx
We are currently reingesting alert data in Kowalski that has been lost. 
In production, this caused issues when users try to access the ztf alert page for a given alert, if its aux data (aggregate of the prv_candidates + cross matches) hasn't been recovered yet.
This PR does:
- if aux data is missing, append the full alert history to effectively give the user all the detections (only the non-detections are now missing).
- if the aux data is missing, show a yellow warning on the frontend, which on hover explains what process we are going through right now, and what data is still available.
=> Temporary bugfix: prevent alert page from crashing when aux data is missing

extensions/skyportal/skyportal/handlers/api/kowalski_filter.py, extensions/skyportal/static/js/components/FilterPlugins.jsx
To prevent sending multiple triggers, and in general, to make sure that follow-up requests are shared with who should see them, we make it possible from Fritz's filter page to specify target_group_ids to use (on top of the filter's group id which is always there) when sending the request.
This PR has an associated Kowalski PR here: 
https://github.com/skyportal/kowalski/pull/255
=> Kowalski Filters - Autofollowup: set target group ids

extensions/skyportal/static/js/components/FilterPlugins.jsx
It looks like the current code does not make a copy as expected (probably, it does make a copy but of the lookup dict, which then still points to the original form).
This PR (untested yet) should fix that by first accessing the form in the lookup, and then making a copy of it.
The last option, which is not as "clean" but always works, is to JSON.stringify and then JSON.parse.
=> Kowalski filter auto-followup: don't edit original form

extensions/skyportal/static/js/components/FilterPlugins.jsx
Honestly who came up with Javascript 🤡
=> Kowalski filter: instrument form copy fix

extensions/skyportal/skyportal/handlers/api/kowalski_filter.py, extensions/skyportal/static/js/components/FilterPlugins.jsx
Add support for:
- autosave.saver_id, allowing Kowalski to use a different user account to autosave candidates as sources to a group, useful to not have everything posted by the `kowalski-bot` account both for book-keeping and to allow TNS autoreports from properly configured bot accounts.
- auto_followup.priority_order, so Kowalski knows if the instrument API associated to the allocation selected has descending or ascending priority values.
- auto_followup.implements_update, so Kowalski knows if the priority of an existing request can be updated or not.
=> Kowalski filters: support new keywords

extensions/skyportal/skyportal/handlers/api/alert.py
At least now things won't be as confusing when adding data from an alert page vs when Kowalski sends the data to Fritz.
Next up is figuring out how we display the negative fluxes because everything in SkyPortal is designed to show negative flux measurements as non-detections, and its not so straightforward to make that customizable on a user basis.
=> WIP: negative fluxes when importing ZTF alert photometry

extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/skyportal/handlers/api/archive.py, extensions/skyportal/skyportal/handlers/api/db_stats.py, extensions/skyportal/skyportal/handlers/api/kowalski_filter.py, fritz.defaults.yaml
This PR:
- adds fritz.science and preview.fritz.science as the list of servers to include in the auto-generated openapi specification.
- adds a `summary` to all of the endpoints Fritz adds on top of SkyPortal. This is required if we want to have a nice text rather than the raw URL shown in the list of endpoints on the left of the API documentation page.
=> Documentation -> server list and endpoint summary

extensions/skyportal/skyportal/handlers/api/kowalski_filter.py, extensions/skyportal/static/js/components/filter/FilterPlugins.jsx, fritz.defaults.yaml
Add support for a new SkyPortal follow-up constraint (https://github.com/skyportal/skyportal/pull/5317) that can be used with Kowalski's auto triggering feature (https://github.com/skyportal/kowalski/pull/444).
This PR adds the API code to support it and validate its value, and adds the frontend required to edit it.
=> Kowalski Filter - not_if_tns_reported

extensions/skyportal/skyportal/handlers/api/alert.py
In this PR we:
- add a decorator on top of each kowalski-related endpoints in `alert.py` which checks if kowalski is available. If it isn't then it tries to connect again before proceeding with the API call itself
- wrapped the Kowalski instantiation in a method that can be called by the decorator
- refactored the ztf alert cutouts import in a separate method
- cleaned up some of the code here and there, avoiding unnecessary operations and writes to disk when creating thumbnails
The original plan was to improve on performance but first it would be good to make the code a bit more robust to avoid running in some errors and such. There is still more work needed but this is a good first step.
=> alert.py: minor improvements
