fritz-marshal/fritz

README.md, fritz
Follow the simple instructions in `readme.md` to run the bare-bones end-to-end demo. For this to work, [this PR on `skyportal`](https://github.com/skyportal/skyportal/pull/400) needs to be addressed and merged first.
=> Bare-bones end-to-end demo

.github/workflows/build-and-deploy-docs.yaml
This is a first step towards continuous integration.  Once the docs build and deploy successfully, I will add the linters, and finally we can add a check on the whole system's integrity.
=> Add GitHub Action to build and deploy docs

README.md, doc/user_guide.md, extensions/skyportal/static/js/components/Alerts.jsx, fritz, fritz.defaults.yaml, tools/check_environment.py
In this PR:
- `update` command in the `fritz` utility
- update config file `fritz.yaml` when necessary
- check `docker` and `docker-compose` versions
- add `GroupSources` SP component to default config
- Trim entered `objectId` on Alerts page
- pin latest SP and K
=> Update fritz.yaml when necessary ++

fritz
Build build, get the git log and send it into SP so it can be used therein.
=> add git logging to the SP data dir

extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/static/js/components/ZTFAlert.jsx, fritz.defaults.yaml
SQLAlchemy was sometimes unhappy about the async calls I put in -- would drop the db connection prematurely. Should investigate this at some point, but switching to sync calls for now.
=> Switch back to synchronous Kowalski calls

fritz.defaults.yaml
Adds upload spectrum component to fritz frontend
=> add upload spectrum component to fritz config

extensions/skyportal/skyportal/handlers/api/alert.py
This PR ports over the thumbnail improvements already merged in Kowalski [#24](https://github.com/dmitryduev/kowalski/pull/24), which indeed make the thumbnails look much better.
=> Further improve thumbnail scaling

extensions/skyportal/data/telescopes_fritz.yaml
Fixes https://github.com/fritz-marshal/fritz-beta-feedback/issues/29.
Blocked by 
https://github.com/skyportal/skyportal/pull/1377
https://github.com/skyportal/skyportal/pull/1378
=> Fix telescope coordinates in telescopes_fritz.yaml

extensions/skyportal/skyportal/app_server_fritz.py, fritz, requirements.txt
=> Include Fritz-specific API in docs

extensions/skyportal/skyportal/handlers/api/alert.py
Which controls whether to pull photometry history for `<objectId>` or not (defaults to True). That is potentially a lot of data that is not always necessary.
=> Add includePrvCandidates param to /api/alerts/ztf/<objectId>/aux

.github/workflows/test-integration.yaml, .pre-commit-config.yaml, doc/conf.py, extensions/skyportal/skyportal/app_server_fritz.py, extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/skyportal/handlers/api/kowalski_filter.py, extensions/skyportal/skyportal/tests/api/test_alerts.py, fritz, fritz.defaults.yaml, tools/check_environment.py, tools/status.py
In this PR:
- Integration (between K and SP) testing GH action that builds Fritz and runs ZTF alert processing/ingestion on K with posting to SP
- Related changes in `fritz`: get Docker gateway IP, wait for all containers to come up before testing etc.
- Update pre-commit hooks
- Set up `black` and lint the codebase
- Update default config
- quite a few recent updates in K's and SP's configs were missing
=> Integration testing on CI

doc/license.md
Closes https://github.com/fritz-marshal/fritz/issues/137
=> Correctly include license

fritz.defaults.yaml
Propagate the latest TNS-related additions on K.
=> Update default config

extensions/skyportal/skyportal/handlers/api/db_stats.py
The front-end component already renders arbitrary data, so no update needed there
See #162
=> Add num alerts ingested today to DB Stats handler info

extensions/skyportal/static/js/components/ZTFAlert.jsx
=> Make Alerts table fill available space

doc/data/filter_examples/watchlist.json, doc/user_guide.md
Prompted by a request from Shri, I had a revelation on how to easily implement watchlists (see https://github.com/skyportal/skyportal/issues/1165) using our existing alert filtering infrastructure. 
This PR adds a section to the user guide with a detailed description of what needs to be done (which is essentially mostly copy-pasting).
=> Watchlists

.gitignore, extensions/skyportal/skyportal/app_server_fritz.py, extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/skyportal/tests/api/test_alerts.py, extensions/skyportal/static/js/components/Alerts.jsx, extensions/skyportal/static/js/components/ZTFAlert.jsx, extensions/skyportal/static/js/components/ZTFAlertsByCoords.jsx, extensions/skyportal/static/js/ducks/alertsByCoords.js, fritz.defaults.yaml
This PR allows users to search for alerts by location.
Closes https://github.com/fritz-marshal/fritz-beta-feedback/issues/75
=> Search for alerts by coordinates

doc/user_guide.md, fritz
This PR brings the quick start docs up to date with new screen captures and more detailed discussions of various workflows.
=> Update quick start docs

extensions/skyportal/skyportal/handlers/api/alert.py
Current docstring is misleading - the data retrieval is successful
=> Update alert aux handler success response in docs

extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/skyportal/handlers/api/kowalski_filter.py
@dmitryduev I did part of the alert handler here -- just showing you what it'd look like so far. Shall I leave the rest for you to do, as you requested?
=> Update DB queries

extensions/skyportal/static/js/components/About.jsx
This should fix the log entry prefix rendering.
=> Update About to match SkyPortal

extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/static/js/components/TNSInfo.jsx
+ take into account that there could potentially be multiple matches, although that is rare.
Proof that it actually works:  :)
=> Fix TNS name display

extensions/skyportal/skyportal/handlers/api/tns_info.py, extensions/skyportal/static/js/components/CandidateList.jsx, extensions/skyportal/static/js/components/TNSInfo.jsx, extensions/skyportal/static/js/ducks/tnsInfo.js
Closes https://github.com/fritz-marshal/fritz/issues/130
=> Show TNS info on scanning page

extensions/skyportal/static/js/components/TNSInfo.jsx
Closes https://github.com/fritz-marshal/fritz/issues/277
=> Update TNSInfo requests submitted internal state logic

doc/user_guide.md, extensions/skyportal/skyportal/handlers/api/archive.py
Now https will be chosen to communicate with the API if config["server.ssl"] is set.
=> Fix bug in archive.py

extensions/skyportal/static/js/components/CandidateList.jsx
Matches changes in skyportal/skyportal#1989
=> Changes to CandidateList.jsx to support scanning profiles

extensions/skyportal/static/js/components/ArchiveSearchButton.jsx
=> Fix bug in ArchiveSearchButton.jsx

extensions/skyportal/static/js/components/SourceDesktop.jsx
=> Make centroid plot size more responsive

extensions/skyportal/static/js/components/GroupFiltersStreams.jsx
Addresses https://github.com/fritz-marshal/fritz/issues/207.
=> Deleting a filter on Fritz's SkyPortal deactivates the corresponding filter_v on Kowalski, if such exists

extensions/skyportal/static/js/components/SourceDesktop.jsx
This just copies code in skyportal which puts the spectroscopy buttons into their own div and makes the spectroscopy plot scrollable
=> Put spectrosocpy buttons into their own div

extensions/skyportal/static/js/components/SourceDesktop.jsx, extensions/skyportal/static/js/components/SourceMobile.jsx
Update source components to align with new skyportal changes
=> update sourcemobile + sourcedesktop

extensions/skyportal/static/js/components/SourceDesktop.jsx, extensions/skyportal/static/js/components/SourceMobile.jsx
This PR adds arguments to FollowupRequestLists to enable pagination.
=> Prepare for follow-up page pagination

extensions/skyportal/static/js/components/SourceDesktop.jsx, extensions/skyportal/static/js/components/ZTFAlert.jsx
Same changes as in [#2888](https://github.com/skyportal/skyportal/pull/2888)
=> Remove ResizeObserver from source page

extensions/skyportal/static/js/components/ZTFAlert.jsx
This PR adds a console log statement to ZTFAlert to help debug.
=> Log ZTFAlert

extensions/skyportal/static/js/components/ZTFAlert.jsx
This PR adds the router to ZTFAlert.
=> Add router to ZTFAlert

extensions/skyportal/static/js/components/SourceDesktop.jsx, extensions/skyportal/static/js/components/SourceMobile.jsx
Because of some extra buttons, SourceDesktop.jsx and SourceMobile.jsx were not updated with skyportal's new modifications. This PR aims to make these modifications manually as requested in https://github.com/skyportal/skyportal/pull/3143.
=> Update Source Page as in Skyportal

extensions/skyportal/static/js/components/SourceDesktop.jsx
Follows the SP merge (https://github.com/skyportal/skyportal/pull/3189)
=> harmonize source desktop with new analysis panel

extensions/skyportal/data/db_fritz.yaml, fritz.defaults.yaml
This PR adds missing skyportal configs to fritz.
=> Add missing skyportal configs to fritz

fritz.defaults.yaml
This PR moves the gcn parameters out by one indent.
=> Move gcn config out one level

extensions/skyportal/data/taxonomy_fritz.yaml
This PR restricts the demo data to groups that exist.
=> Fix group_ids in demo taxonomy data

fritz.defaults.yaml
This PR adds analysis pages to the fritz config.
=> Add analysis pages

fritz.defaults.yaml
This PR adds the Swift XRT endpoint to the config.
=> Add Swift XRT endpoint

extensions/skyportal/static/js/components/ZTFAlert.jsx
This PR adds a photometry update button for ZTF alerts.
=> Photometry button enabled for ZTF alerts

extensions/skyportal/skyportal/handlers/api/alert.py
This PR refactors the alert handler to simplify calls from other handlers.
=> Refactor alert handler

extensions/skyportal/skyportal/app_server_fritz.py, extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/static/js/components/Alerts.jsx
This PR adds a button to specifically retrieve thumbnails for an object.
=> Add alert thumbnail retrieval

extensions/skyportal/skyportal/handlers/api/db_stats.py
This PR adds more DB statistics (Comments, Annotations, etc.)
=> Add more DB stats

extensions/skyportal/static/js/components/FilterPlugins.jsx
This PR adds dark theme in filter plugins.
=> Add dark theme in filter plugins

extensions/skyportal/skyportal/handlers/api/db_stats.py
For a large DB, the candidates timing queries are prohibitive (and I don't see the use to them). So let's remove them.
=> Remove slow db_stats queries

extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/static/js/components/ZTFAlert.jsx
This PR adds default arguments for post_alert.
=> Default arguments for post_alert

extensions/skyportal/static/js/components/FilterPlugins.jsx
This PR attempts to fix the missing group bug in FilterPlugins.
=> Fix missing group bug

.gitmodules, extensions/skyportal/skyportal/handlers/api/archive.py, extensions/skyportal/skyportal/handlers/api/db_stats.py, extensions/skyportal/static/js/components/FilterPlugins.jsx, fritz.defaults.yaml, launcher/commands/test.py
This PR updates a few config files to 
1. Add WINTER/SUMMER instruments on Fritz
2. Add a WINTER alert stream
3. Include WINTER in the kowalski section of fritz.defaults.yaml (essentially replaces the existing section with [this](https://github.com/skyportal/kowalski/blob/master/config.defaults.yaml)
4. Pins kowalski and skyportal to versions that include WINTER
=> Add WINTER

extensions/skyportal/skyportal/handlers/api/alert.py
This PR fixes program_id_selector to be a list.
=> program_id_selector list

fritz.defaults.yaml
This PR adds dustmap data to the config.
=> Add dustmap data

fritz.defaults.yaml
This PR adds the allocation summary to Fritz config.
=> Add allocation summary to config

extensions/skyportal/static/js/components/SaveAlertButton.jsx
This PR fixes the save alert button validation.
=> Save alert button validation

extensions/skyportal/skyportal/handlers/api/archive.py, extensions/skyportal/static/js/components/Archive.jsx
This PR adds more flexibility to archive saving.
=> Archive saving

fritz.defaults.yaml
This PR adds the persistent data comment folder.
=> Persistent data comment folder

extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/static/js/components/SaveAlertButton.jsx, extensions/skyportal/static/js/components/ZTFAlert.jsx
This PR shows saved groups on alert page.
=> Saved groups on alert page

extensions/skyportal/skyportal/handlers/api/alert.py
This PR extends thumbnail endpoint to grab all for an object.
=> Grab all thumbnails

extensions/skyportal/static/js/components/Archive.jsx, extensions/skyportal/static/js/components/ArchiveSearchButton.jsx
Hi reviewers. I haven't had the chance to run this code yet but I believe this could help prevent the source page crash in production. Please try running it before merging. I will try to do so myself and leave an "edit" here.
=> catalogNames.filter type safety

extensions/skyportal/static/js/components/Archive.jsx
This PR checks for a source of same name for saving.
=> Persistent source names

extensions/skyportal/static/js/components/Archive.jsx, fritz.defaults.yaml
This PR fixes the Archive default catalog query.
=> Default catalog archive query

extensions/skyportal/static/js/components/Alerts.jsx, fritz.defaults.yaml
Added the new BTS score to the /alerts page
=> added bts score to alert page

fritz.defaults.yaml
This PR updates default database arguments.
=> Database arguments

extensions/skyportal/skyportal/handlers/api/alert.py, extensions/skyportal/static/js/components/Alerts.jsx, extensions/skyportal/static/js/ducks/alerts.js
This PR enables multiple object name alert queries.
=> Alert query for multiple object IDs

extensions/skyportal/static/js/components/Alerts.jsx, extensions/skyportal/static/js/ducks/alerts.js
This PR checks for non-null object_id in alert query.
=> Non-null object_id in alert query

extensions/skyportal/skyportal/handlers/api/tns_info.py
We got some down times in prod when Kowalski returns something that is unexpected.
=> TNS info endpoint: wrap in try except

extensions/skyportal/static/js/components/Alerts.jsx, extensions/skyportal/static/js/components/Archive.jsx
This PR allows users to use different units when specifying a radius for a conesearch on the Alerts and Persistent sources pages.
=> Alert/Persistent search: radius units

fritz.defaults.yaml
Change port to not interfere with a port used by an API app
=> TNS submission queue port change

extensions/skyportal/skyportal/handlers/api/kowalski_filter.py, extensions/skyportal/static/js/components/FilterPlugins.jsx, extensions/skyportal/static/js/ducks/kowalski_filter.js
This PR modifies the current Kowalski filters backend and frontend to support the recent additions made to Kowalski's filters, which make auto follow-up request triggering, and conditional autosave possible.
These changes also required me to add new features to SkyPortal, so this PR also pins the latest version of SP.
=> Kowalski filters: Auto followup option, advanced autosave

extensions/skyportal/skyportal/handlers/api/archive.py
This PR adds an associated user to pass to post_source.
=> Associated user to pass to post_source

extensions/skyportal/skyportal/handlers/api/archive.py
This PR checks for user or token.
=> archive user or token

extensions/skyportal/skyportal/handlers/api/alert.py
This PR fixes an error checking for stream_id.
=> stream_id check error

extensions/skyportal/skyportal/handlers/api/alert.py
I noticed that the `add_external_photometry()` method that the Fritz-specific AlertHandler POST method relied on (through the `post_alert()` function) treated group_ids and stream_ids as something to enforce on all datapoints (which to be fair is exactly how it is used everywhere else in the app!).
So here we simply batch photometry per stream and call `add_external_photometry()` on each batch to make sure that the stream data access is correct on these datapoints.
=> ZTF Alert Post: stream data access issue

extensions/skyportal/skyportal/handlers/api/archive.py
This PR checks if lightcurve_ids is an integer and therefore need to be a list.
=> make lightcurve_ids list if needed

.github/workflows/build-test-doc_upload.yaml, fritz.defaults.yaml, launcher/commands/build.py, launcher/commands/doc.py, launcher/commands/log.py, launcher/commands/run.py, launcher/commands/stop.py, launcher/commands/test.py, launcher/skyportal.py, tools/check_environment.py
docker-compose is now called with `docker compose` (space instead of a dash), and the the containers are not called `skyportal_web_1`, but `skyportal-web-1` (dashes instead of underscores).
This PR makes these changes + pins SkyPortal latest where these changes were made to the CI and `docker-compose.yaml` config too.
=> Docker compose update: migrate to new container name syntax

extensions/skyportal/skyportal/handlers/api/kowalski_filter.py, extensions/skyportal/static/js/components/filter/FilterPlugins.jsx
Support for Kowalski+SP latest addition, that when editing a filter (with automated triggers turned on) lets a user set a list of allocations, that if any pending/completed requests exist for any of them, a new request's submission can be canceled.
=> Kowalski filter auto followup: ignore_allocation_ids

extensions/skyportal/static/js/components/alert/ZTFAlert.jsx
Fix new checksource function not working on Fritz
=> Fix new checksource function not working on Fritz
